services:
  db:
    image: mysql:8.0
    container_name: springdb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
      MYSQL_USER: springdb
      MYSQL_PASSWORD: springdb
    ports:
      - "3306:3306"
    volumes:
      - p3_spring_data:/var/lib/mysql
    networks:
      - p3_spring

  pma:
    image: arm64v8/phpmyadmin
    container_name: springpma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - p3_spring

volumes:
  p3_spring_data: {}

networks:
  p3_spring: {}
